sudo: required

dist: xenial

language: minimal

services:
  - docker

before_install:
  - set -e
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker build -t augis91/musu-biudzetas --build-arg GIT_COMMIT=${TRAVIS_COMMIT::8} .
  - docker push augis91/musu-biudzetas
  - openssl aes-256-cbc -K $encrypted_4fbf55944ba9_key -iv $encrypted_4fbf55944ba9_iv -in deploy_mb_rsa.enc -out /tmp/deploy_mb_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_mb_rsa
  - ssh-add /tmp/deploy_mb_rsa
  - set +e

after_success:
  - set -e
  - ssh -o "StrictHostKeyChecking no" -i /tmp/deploy_mb_rsa $REMOTE_USER@$REMOTE_HOST 'bash -s' < config/deploy-travis.sh
  - set +e

branches:
  only:
    - master
