varsion: "3.4"
 
 services:
  postgres:
    image: postgres:10.5
    env_file:
      - .env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  platform:
    image: augis91/musubiudzetas
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ || exit 1"]
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        delay: 5s
        order: stop-first
    volumes:
      - static_volume:/srv/musubiudzetas/static
      - media_volume:/srv/musubiudzetas/media
    networks:
      - nginx_network
      - database_network
      - datadog_network
    depends_on:
      - postgres

  nginx:
      image: nginx:1.15
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./config/nginx/conf.d:/etc/nginx/conf.d
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        - static_volume:/srv/musubiudzetas/static
        - media_volume:/srv/musubiudzetas/media
      depends_on:
        - musubiudzetas
      networks:
        - nginx_network
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure