# Generated by Django 2.2.8 on 2020-01-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200129_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_cat',
            field=models.IntegerField(blank=True, choices=[(1, 'Viešasis sektorius'), (2, 'Privatus sektorius'), (3, 'Nevyriausybinis sektorius'), (4, 'Kitos, nepelno organizacijos')], null=True, verbose_name='Juridinio asmens sektorius'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Asociacija'), (2, 'Bendrija'), (3, 'Biudžetinė įstaiga'), (4, 'Labdaros ir paramos fondas'), (5, 'Politinė partija'), (6, 'Prekybos, pramonės ir amatų rūmai'), (7, 'Profesinė sąjunga ar susivienijimas'), (8, 'Religinė bendruomenė ar bendrija'), (9, 'Sodininkų bendrija'), (10, 'Šeimyna'), (11, 'Tradicinė religinė bendruomenė ar bendrija'), (12, 'Viešoji įstaiga'), (13, 'UAB'), (14, 'AB'), (15, 'Individuali Veikla'), (16, 'Mažoji Bendrija'), (17, 'Asociacijos filialas'), (18, 'Individuali Įmonė'), (19, 'Draugija'), (20, 'Kita')], null=True, verbose_name='Juridinio asmens tipas'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='pub_sector',
            field=models.IntegerField(blank=True, choices=[(1, 'Sportas'), (2, 'Kultūra'), (3, 'Socialinė apsauga'), (4, 'Sveikatos apsauga'), (5, 'Švietimas'), (6, 'NVO'), (7, 'Aplinkos apsauga'), (8, 'Žmogaus teisės, demokratija')], null=True, verbose_name='Viešosios politikos sritis'),
        ),
    ]
