# Generated by Django 2.2.8 on 2020-01-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200130_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='region',
            field=models.IntegerField(choices=[(1, 'Alytaus apskritis'), (2, 'Kauno apskritis'), (3, 'Klaipėdos apskritis'), (4, 'Marijampolės apskritis'), (5, 'Panevėžio apskritis'), (6, 'Šiaulių apskritis'), (7, 'Tauragės apskritis'), (8, 'Telšių apskritis'), (9, 'Utenos apskritis'), (10, 'Vilniaus apskritis')], verbose_name='Apskritis'),
        ),
    ]
