# Generated by Django 2.2.3 on 2019-07-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190713_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='short_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Savivaldybės sutrumpintas pavadinimas'),
        ),
    ]
