# Generated by Django 2.2.3 on 2019-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190715_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['slug'], 'verbose_name': 'Savivaldybė', 'verbose_name_plural': 'Savivaldybės'},
        ),
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Biudžeto pavadinimas'),
        ),
    ]
