# Generated by Django 2.2.3 on 2019-07-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190716_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='municipality_id',
            new_name='municipality',
        ),
    ]
