# Generated by Django 2.2.3 on 2019-07-21 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190721_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Juridinio asmens sektorius')),
                ('slug', models.SlugField(unique=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juridinio asmens sektorius',
                'verbose_name_plural': 'Juridinio asmens sektoriai',
                'ordering': ['slug'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EntitySector', verbose_name='Juridinio asmens kategorija'),
        ),
        migrations.DeleteModel(
            name='EntityCategory',
        ),
    ]
