# Generated by Django 2.2.3 on 2019-07-21 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190721_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicsector',
            options={'ordering': ['slug'], 'verbose_name': 'Viešosios politikos sritis', 'verbose_name_plural': 'Viešosios politikos sritys'},
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EntitySector', verbose_name='Juridinio asmens sektorius'),
        ),
    ]
