# Generated by Django 2.2.3 on 2019-07-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190721_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='budget',
            field=models.ManyToManyField(blank=True, to='app.Budget', verbose_name='Biudžetas'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='program_participant',
            field=models.ManyToManyField(blank=True, help_text='Programa, iš kurios yra gaunamas finansavimas', to='app.Program', verbose_name='Programa'),
        ),
    ]
