# Generated by Django 2.2.3 on 2019-07-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190721_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='pub_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PublicSector', verbose_name='Viešosios politikos sritis'),
        ),
    ]
