# Generated by Django 2.2.3 on 2019-07-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190721_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['year', 'amount'], 'verbose_name': 'Biudžetas', 'verbose_name_plural': 'Biudžetai'},
        ),
        migrations.AddField(
            model_name='budget',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'Savivaldybės finansavimas'), (2, 'Valstybės finansavimas'), (3, '2 proc. GPM'), (4, 'Gyventojų parama'), (5, 'Kitos pajamos'), (6, 'Bendras biudžetas')], default=1, verbose_name='Finansavimo šaltinis'),
        ),
        migrations.AddField(
            model_name='entity',
            name='accounts_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Finansinių ataskaitų šaltinis Registrų centre'),
        ),
        migrations.AddField(
            model_name='entity',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Pastabos'),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_accountable',
            field=models.BooleanField(null=True, verbose_name='Ar teikia ataskaitas?'),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_funder',
            field=models.BooleanField(null=True, verbose_name='Finansuotojas'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='adult_pop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gyventojų skaičius nuo 17 iki 65 metų'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Savivaldybės plotas'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='m_child_pop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gyentojų skaičius nuo 6 iki 17 metų'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='s_child_pop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gyventojų skaičius nuo 0 iki 6 metų'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='senior_pop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Gyventojų skaičius nuo 65 metų'),
        ),
    ]
