# Generated by Django 2.2.3 on 2019-07-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_budget_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='source_type',
            new_name='b_source',
        ),
        migrations.AddField(
            model_name='budget',
            name='b_type',
            field=models.IntegerField(choices=[(1, 'Juridinio asmens biudžetas'), (2, 'Programos biudžetas')], default=1, verbose_name='Biudžeto tipas'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='legal_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Įmonės kodas'),
        ),
    ]
