# Generated by Django 2.2.3 on 2019-07-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190728_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='program',
            name='budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Entity', to_field='legal_id', verbose_name='Juridinis asmuo'),
        ),
        migrations.AddField(
            model_name='budget',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Program', verbose_name='Programa'),
        ),
    ]
