# Generated by Django 2.2.3 on 2019-08-16 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190728_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='m_child_pop',
            new_name='child_pop',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='s_child_pop',
        ),
        migrations.AlterField(
            model_name='program',
            name='fund_source_entity',
            field=models.ForeignKey(limit_choices_to={'is_funder': True}, on_delete=django.db.models.deletion.CASCADE, to='app.Entity', verbose_name='Finansuotojas'),
        ),
    ]
