# Generated by Django 2.2.4 on 2019-08-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190823_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
