# Generated by Django 2.2.4 on 2019-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20190823_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
