# Generated by Django 2.2.4 on 2019-08-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190823_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_funder',
        ),
    ]
