# Generated by Django 2.2.4 on 2019-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_entity_is_funder'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_funder',
            field=models.BooleanField(null=True, verbose_name='Finansuotojas'),
        ),
    ]
