# Generated by Django 2.2.4 on 2019-08-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_entity_is_funder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='program_participant',
        ),
    ]
