# Generated by Django 2.2.4 on 2019-08-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_entity_program_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='currency',
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Suma, EUR'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
