# Generated by Django 2.2.4 on 2019-08-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190824_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_ministry',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Ar ministerija?'),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_municipality',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='Ar savivaldybės administracija?'),
        ),
    ]
